server:
  # Puerto del servidor
  port: 8081
  servlet:
    context-path: /seguimiento_back/v1
spring:
  application:
    name: login
  profiles:
    active: local
    main:
      banner-mode: off


  datasource:
    url: jdbc:mysql://localhost:3306/seguimiento?useSSL=false&serverTimezone=UTC
    username: root
    password: Suncion123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: myapplication.log
  level:
    org.springframework: ERROR
    com.example: DEBUG

security:
  enabled: true
  allowed-urls-origin: http://localhost:4200,http://localhost:4300,http://192.168.125.249:8080,http://172.16.15.91:8080,http://192.168.56.1:8181,http://192.168.56.1:8080,http://172.29.48.1:7001,https://c.tile.openstreetmap.org,https://unpkg.com,http://localhost:8080

  exclude-path-patterns:
    /**/openapi/**,
    /**/swagger-resources/**,
    /**/webjars/swagger-resources/**,
    /**/webjars/springfox-swagger-ui/**,
    /**/error,
    /**/swagger-ui.html/**,
    /**/favicon.ico,
    /**/actuator/**,
    /**/actuator/
